### ISSUE TITLE
trash in project dir

### ISSUE THREAD

**Issue by akaRem** [ostinelli/gin#21]
vagrant@vagrant:/vagrant/data/testapp$ ls 
app  client_body_temp  config  db  fastcgi_temp  lib  logs  proxy_temp  scgi_temp  spec  tmp  uwsgi_temp

its not good to strt nginx from local dir.
this totally pollutes it with tempdirs :(

**Comment by ostinelli** [comment]
Indeed. Any recommendations?

**Comment by leite** [comment]
why not all *_tmp inside tmp - is a good start.

try adding this into you nginx.conf inside http scope ...
```nginx

    proxy_temp_path tmp;
    client_body_temp_path tmp;
    fastcgi_temp_path tmp;
    scgi_temp_path tmp;
    uwsgi_temp_path tmp;
```

**Comment by ostinelli** [comment]
Added.
