### ISSUE TITLE
Transform Test Cases to Use busted 2.0

### ISSUE THREAD

**Issue by istr** [ostinelli/gin#25]
As busted 2.0 seems to be nearing a release, I would like to transform the test cases to be compatible with busted 2.0. Currently the test suite fails using 2.0 mainly when pcalls are involved. I would like to investigate and make an upgrade to the test suites. Would that contribution be welcome?

**Comment by idevz** [comment]
i vote for this

**Comment by ostinelli** [comment]
Yes. :)

**Comment by istr** [comment]
Ok, will create a branch based on current master.

**Comment by ostinelli** [comment]
Great. Thank you.

**Comment by istr** [comment]
Repacked https://github.com/ostinelli/gin/pull/26 into https://github.com/ostinelli/gin/pull/29 and adapted travis script to call ```busted``` instead of ```busted_bootstrap``` such that https://github.com/ostinelli/gin/pull/29 passes travis CI builds. Thanks again, @leite for really resolving this issue.

**Comment by istr** [comment]
Closing. [PR was merged](https://github.com/ostinelli/gin/pull/29). Thanks a lot.
