### ISSUE TITLE
ORM by itself?

### ISSUE THREAD

**Issue by andreasbhansen** [ostinelli/gin#33]
Hi,

So for the time being, I'm working with some Lua scripts requiring database access. I don't need the entire Gin framework, only the [**Models**](http://gin.io/docs/models.html)/ORM as it seems far superior to anything related I've come across so far.

Is there a way to use it without OpenResty and the rest of the Gin (API related) framework?

**Comment by jtarchie** [comment]
I don't think so. I believe it relies on the OpenResty database drivers.

**Comment by ostinelli** [comment]
Hi, as per @jtarchie 's response I had to rely on internal OpenResty drivers so no additional work has been provided to make the ORMs and migrations work as standalones.

If needed, it is possible to extract the ORM and migration engines from here:
https://github.com/ostinelli/gin/tree/master/gin/db
